### PR TITLE
Fixes silver script on macOS.

### PR DESCRIPTION
**Pull request by remexre**
Can someone with a Mac test this?

### CODE REVIEW

**Comment by tedinski** [comment]
I haven't tested it, but if it's good, please close #95 I guess.

**Comment by remexre** [comment]
I haven't either; I'm probably going to ask whichever Mac user I see first
tomorrow to try it out.

**Comment by ericvanwyk** [comment]
I'll try it tomorrow.

Also, on my agenda is to get a Mac that everyone can login to so that this
can be tested by anyone.

-Eric

**Comment by tedinski** [comment]
Ok. Tested, works. Merging.

**Pull request merged**
