### PR TITLE
Revert "Feature/monto+highlight"

### PR DESCRIPTION
**Pull request by krame505**
Reverts melt-umn/silver#134

### CODE REVIEW

**Comment by tedinski** [comment]
wait what?

**Comment by krame505** [comment]
We agreed to temporarily roll this back until the IDE is fixed.  Now the published jars are for the version including this branch, so I can't run `deep-rebuild`.  Now what?

**Comment by tedinski** [comment]
Okay. Short coordination discussion.

Right now we've got a few things going wrong ("everything is on fire" -Lucas's appropriate description).

1. The biggest issue is a bunch of builds are broken because of my brilliant addition of `concat` to `core`.
2. The next biggest issue is there are several bugs introduced as a result of this work.
3. Jenkins is presently busted. Ugh.

I would like to work on 2 right now, but reverting this merge stops me from doing that. From the other thread, I thought you were working on item 1.

**Comment by krame505** [comment]
When was the last time we published jars?  If we haven't since this pull request got merged, then there should still be a backup somewhere we can restore, right?

**Comment by tedinski** [comment]
You should be able to download build artifacts from jenkins. It appears it isn't so broken that this isn't possible.

I really wish you hadn't done this revert. Github no longer seems to think there are any changes in the monto feature branch. I think it has only made the situation more complicated.

**Pull request merged**
