### PR TITLE
Adds build-everything script.

### LINKED ISSUE #130: deep-rebuild doesn't rebuild all grammars
`./deep-rebuild` only rebuilds grammars `silver:composed:Default` depends on -- should this be changed?

### PR DESCRIPTION
**Pull request by remexre**
Closes #130.

This also deletes two grammars:

`lib:langproc:tests` doesn't build.
`silver:composed:monto` hasn't worked for a while, and won't in the near future.

### CODE REVIEW

**Comment by tedinski** [comment]
As long as you're removing `langproc:tests` with this, I endorse removing `langproc` entirely I think.

You'll need to remove the import of it from that one build everything grammar in the documentation extension.

**Comment by remexre** [comment]
Removed `lib:langproc`, everything else builds properly.

**Comment by remexre** [comment]
@tedinski This OK to merge?

**Comment by tedinski** [comment]
Sure.

**Pull request merged**
