### PR TITLE
Fix issue with semantic tokens for lines containing tabs.

### PR DESCRIPTION
**Pull request by krame505**
# Changes
This PR is based on #695 and should be reviewed after that is merged.

This is a workaround for #690 - just replace tabs with spaces before running the parser, for now.  Also fix a bug with reporting semantic tokens for terminals that begin or end with a newline.

# Documentation
Added a comment about the workaround.

### CODE REVIEW

**Comment by ericvanwyk** [comment]
Does VS Code have settings so that on the editor side, all tabs are replaced by spaces?

**Comment by RandomActsOfGrammar** [comment]
Is there a compelling reason for the Silver behavior of treating tabs as eight spaces, rather than as a single character?  I'm not sure the fix for this is changing the tabs to spaces before parsing, rather than changing the behavior of Silver to treat tabs as a single character.

**Comment by krame505** [comment]
> Does VS Code have settings so that on the editor side, all tabs are replaced by spaces?

There are editor commands to substitute tabs for spaces or vice versa, but I'm not aware of a way to treat tabs as spaces for the purposes of semantic highlighting, though?  

> Is there a compelling reason for the Silver behavior of treating tabs as eight spaces, rather than as a single character? I'm not sure the fix for this is changing the tabs to spaces before parsing, rather than changing the behavior of Silver to treat tabs as a single character.

This is really an issue of how Copper reports locations, not Silver.  

In most editors the column numbers are computed assuming that tabs pad to multiples of some width - so padding is generally the desired behavior, to get error messages to line up with the actual editor location.  In emacs the default is tab width is 8, I'm not sure about other editors.  

But with LSP the token encoding is based on the number of characters, not the visual column index.  Replacing tabs with spaces keeps the character count aligned with the column index computed by Copper, for now.  Properly fixing this would require a change to the API of Copper-generated parsers, which I don't feel like tackling at the moment.

**Comment by ericvanwyk** [comment]
What do white-space sensitive languages like Haskell and Python do for tabs? The language definition must assign them some fixed width, right?

It also seems like `tab` is no longer treated as a character to insert - many times `tab` directs the editor to indent the line in some appropriate way based on what is above it, inserting spaces, I presume, to make that happen. So maybe this problem will/should go away for some editors/languages.

**Comment by krame505** [comment]
Haskell also seems to treat tabs as padding multiples of 8 in reported error column numbers:
```haskell
module Test where

x :: Integer
x =
	"hello"
```

```
Test.hs:5:9: error:
    • Couldn't match expected type ‘Integer’ with actual type ‘[Char]’
    • In the expression: "hello"
      In an equation for ‘x’: x = "hello"
  |
5 |         "hello"
  |         ^^^^^^^
```

Python doesn't report column numbers in error messages. only the line number.

We definitely _should_ support tabs in source files.  We don't use them much in Silver, but they do show up in the java translation in multi-line string templates.

**Comment by ericvanwyk** [comment]
If Haskell treats a tab as equal to 8 spaces then it doesn't seem wrong for us to do the same. I agree with Dawn that the right solution is to handle tabs properly and adjust the Copper API as you say. But just open a ticket for this on Copper's repo as something to be fixed later.

**Comment by krame505** [comment]
Turns out that properly fixing this doesn't actually require any Copper API changes - the `setTabWidth` on the `virtualLocation` in the parser class does what is required.

**Comment by ericvanwyk** [comment]
Cool.

**Review by unironically — APPROVED** [review]

**Pull request merged**
