### PR TITLE
Renaming of partially decorated references to unique references

### PR DESCRIPTION
**Pull request by krame505**
# Changes
* "Partially decorated references" are now referred to as "unique references"
* The type expression syntax `PartiallyDecorated` is changed to `Decorated!` (suggested by @RandomActsOfGrammar)

# Documentation
This will be reflected in the updated docs once feature/uniqueness-analysis is ready to merge.

### CODE REVIEW

**Comment by ericvanwyk** [comment]
Can you indicate the motivation for `Decorated!`?  Does this come from some other language or system?

**Review by ericvanwyk — APPROVED** [review]
Look good - pretty straightforward.

But add something about where the ! comes from. I presume some other system or language uses this symbol for a similar reason.

**Comment by krame505** [comment]
According to @RandomActsOfGrammar:

> In logic, sometimes people write ∃! to mean "there exists a unique item such that".  That's why I suggested it.  I don't know if any other software systems use it.

**Comment by ericvanwyk** [comment]
Something like this should be part of the documentation. Maybe find out more what systems/logics do this.  Thanks.

**Pull request merged**
