### PR TITLE
Feature/lambda

### PR DESCRIPTION
**Pull request by tedinski**
Fixed the bug related to thunk 'context' being captured via this instead of directly (since it gets mutated to null inside Thunk.)

### CODE REVIEW

**Comment by krame505** [comment]
Hi Ted,
Thanks for working on this!  I am getting a large number of compilation errors when compiling the test cases, even after rebuilding with --clean.  Are you sure you committed everything?

**Comment by tedinski** [comment]
self-compile? That won't work for changes like this.

Start with fresh jars (re fetch-jars) and deep-rebuild.

**Comment by krame505** [comment]
Ah, yes, I forgot I had to deep-rebuild when the runtime changes.

**Comment by krame505** [comment]
OK, looks good to me!

**Comment by krame505** [comment]
Oops, meant to merge not close

**Pull request merged**
