### PR TITLE
Replaces CopperRuntime.jar with CopperCompiler.jar.

### PR DESCRIPTION
**Pull request by remexre**
Currently I can't build the IDE tooling (even on `develop`) to check if this broke it, so that's maybe an area of concern.

Otherwise, this'll make it less annoying to finish `feature/copper-api`, and would be part of it anyway.

### CODE REVIEW

**Review by krame505 — APPROVED** [review]
IDE builds and works fine for me, by the way.

**Comment by krame505** [comment]
Wait, actually I do have a question about this.  Is this including the entire CopperCompiler.jar in every Silver jar we build, not just silver.compiler.composed.Default.jar?  If so how much does that increase the total jar size?

**Comment by remexre** [comment]
> Wait, actually I do have a question about this. Is this including the entire CopperCompiler.jar in every Silver jar we build, not just silver.compiler.composed.Default.jar? If so how much does that increase the total jar size?

Oh, hm, I hadn't thought of that... 44MB -> 46MB for ableC.jar, so not a huge increase.

**Comment by krame505** [comment]
Alright, seems fair then.  

We have discussed an ableC-yacc extension where calling into Copper to build a parse table would be somewhat useful - so this would help enable that sort of extension anyway.  In the future if we do go that way, we might consider pulling the Silver FFI bindings for the Copper API into a seperate library under `silver:copper`, perhaps.

**Comment by ericvanwyk** [comment]
So did we just merge the `Compiler` and `Runtime` into one?  Which seems fine to me...

**Comment by remexre** [comment]
> So did we just merge the `Compiler` and `Runtime` into one? Which seems fine to me...

`Compiler` already included `Runtime`, this changes which one we depend on (and stops fetching `Runtime`).

---

Also, about to rebase this onto #428, since it's easier to re-bootstrap this than that. So don't merge this before #428 is ready!

**Comment by remexre** [comment]
rebuilding in light of `feature/typeclass` merge...

**Pull request merged**
