### PR TITLE
Bite the bullet, rename pp functions

### PR DESCRIPTION
**Pull request by tedinski**
Sending for review now. I'll send another pull request to ableC to update it as well.

### CODE REVIEW

**Comment by tedinski** [comment]
@krame505 I choose you! Can you glance over this, and the ableC pull request, and let me know if you see anything?

**Comment by krame505** [comment]
Generally looks fine to me.  
As for the ableC PR, I made the same changes of replacing concat with ppConcat along with some other refactoring in my feature/overloading branch, which will probably cause merge conflicts.  That branch is just about ready to merge, but at this point should we just merge this PR and I'll deal with the conflicts in my branch?

**Comment by tedinski** [comment]
Hm. Would it work if I merge this, and leave you to figure out what to do about ableC? (Would you get it done soon? I want to start messing about with Jenkins...)

FWIW, if you made the exact same change, I think it won't conflict... git is nice that way.

**Comment by krame505** [comment]
There was more reformatting that happened at the same time though so it
probably won't be an automatic merge... but yeah, I would say go ahead and
merge this, and I will fix things in my branch.

Lucas Kramer

**Pull request merged**
