### PR TITLE
Add missing "Expr" to function calls.

### PR DESCRIPTION
**Pull request by jzwolak**
Following the instructions I ran "./update" and "./build-everything", which failed.

I found the problem to be the missing "Expr" on a few function calls in "extension" directory. I corrected them and now build-everything succeeds.

### CODE REVIEW

**Comment by ericvanwyk** [comment]
Thanks, Jason.

@tedinski - do we really want to build everything like this?  This isn't being tested apparently.

Can you also merge Jason's PR - after giving it a quick look.

The extended origins stuff is rather dated and should be looked at again - I'm not sure it was ever completed by Kevin.

**Comment by tedinski** [comment]
Yeah, I'll check over the documentation. This looks like a good change though, so merging.

**Comment by tedinski** [comment]
Hi @jzwolak, I looked but didn't find anything referencing the `build-everything` script in our documentation. Did I miss something, or was this possibly just a misread reference to `deep-rebuild` or something like that?

**Comment by ericvanwyk** [comment]
``build-everything`` is a script in the top level of the Silver repo.  Looks like Nathan added it but I am not sure why.

**Comment by remexre** [comment]
The point of `build-everything` was actually to prevent exactly this :P

Because there's code in the Silver repo not included by the compiler itself, I wanted to make sure that the changes I was making during the Monto stuff (iirc) weren't breaking something that someone else needed.

**Comment by jzwolak** [comment]
Hi Ted, maybe I didn't see it in the docs but just saw it in the top level
directory and thought it made since to run a script called
"build-everything" since I just cloned the repo.

--
Jason Zwolak

**Pull request merged**
