### PR TITLE
Adds start of Monto support for the Silver language itself.

### PR DESCRIPTION
**Pull request by remexre**
**READ THIS BEFORE EVEN THINKING ABOUT MERGING**: There should be an in-person meeting with unanimous agreement between at least @ericvanwyk, @krame505, @remexre, @tedinski, and @TravisCarlson that this should be merged before it is.

Refer to #134, #140, #141, and #142 for history.

---

This branch readds the [`feature/monto+highlight`](https://github.com/melt-umn/silver/pull/134) things [**NOT YET**], as well as adding a Monto service for Silver itself ([`silver:composed:monto`](https://github.com/melt-umn/silver/tree/feature/monto-in-silver/grammars/silver/composed/monto)).

### CODE REVIEW

**Comment by tedinski** [comment]
yeah, this isn't the same as the other branch at all.

**Comment by remexre** [comment]
I think what I'll do is manually readd the changes when I fix the merge conflicts -- this is branched off of `feature/monto+highlight` before it got merged into `develop`, so it doesn't have the revert in its history:

Imgur

**Comment by tedinski** [comment]
But that doesn't help. The revert is still there when its merged.

I like my idea in the other pull request more: we should just add a revert-revert commit to that branch.

**Comment by remexre** [comment]
Closing this in favor of development on the `feature/monto3` branch.

**Pull request closed without merging**
