### PR TITLE
Fix a bug with match rule translation causing a crash when the last rule had too few patterns

### PR DESCRIPTION
**Pull request by krame505**

### CODE REVIEW

**Comment by RandomActsOfGrammar** [comment]
Can you explain what problem this is supposed to fix?  The only production for `AbstractMatchRule` is `matchRule`, so adding a default pattern where you did shouldn't change anything.

**Comment by krame505** [comment]
Yes, but it is matching on `headPat :: restPat` as its first argument which only matches a non-empty list.  It seems that if too few patterns are provided in a rule, this pattern can fail to match.  Adding this case is a workaround that lets the error message be reported.

**Comment by RandomActsOfGrammar** [comment]
I see; it was an incomplete match before you added that.  However, my (admittedly few) attempts to trigger the original code into crashing instead of giving an error message aren't working.  Do you have a small crashing example?

**Comment by krame505** [comment]
Umm no, this was something I ran into when experimenting in ableC.  I don't remember exactly what the code was that triggered this, but I did test that this change fixed the crash.

**Comment by krame505** [comment]
I think it was a case expression matching on two values, where the last case only had one pattern in the pattern list.

**Comment by RandomActsOfGrammar** [comment]
The number of patterns is getting checked on the concrete productions of type `MatchRule`.  For this to cause an error, your example must be bypassing the concrete productions.  That should be fixed as well.

What error message do you get with this fix?  I'm not sure where that would be coming from, since the code looks like it just assumes there will be enough patterns after the concrete productions are gone.

I want to be sure this is the right fix, rather than adding some other check elsewhere.

**Comment by krame505** [comment]
I am getting the expected error message from the concrete `MatchRule`, now.  The issue is that translation is still being demanded even when there are errors in the concrete `MRuleList` due to how pattern error checking is structured.  This was resulting in a crash in computing the translation, before the concrete MatchRule error message could be reported.

**Comment by RandomActsOfGrammar** [comment]
That seems like something that should be fixed, but that is another issue.

**Review by RandomActsOfGrammar — APPROVED** [review]

**Comment by krame505** [comment]
The issue stems from how pattern matching is poorly divided into an extension and a modification, such that most (but not all) of the checking happens on what the extension forwards to.  Really the extension should handle all of the checking and the modification should just be there providing primitives to deal with productions, probably.  This is complicated a bit by needing to support GADT productions, I think.  

We already have a few open issues that touch on this (e.g. #76.)

**Pull request merged**
