### PR TITLE
When clauses for pattern matching

### PR DESCRIPTION
**Pull request by RandomActsOfGrammar**
This adds `when` clauses to pattern matching with `case`, allowing Boolean conditions to be added to match clauses.  This enables something like the following code to be written:
```
case x of
| bar(_, _) -> 5
| foo(a,b) when a > b -> a - b
| foo(a,b) when b > a -> b - a
| _ -> 0
end
```

### CODE REVIEW

**Comment by krame505** [comment]
FYI Jenkins is still slightly broken, so you'll need to trigger a build manually before github will let you merge.

**Comment by RandomActsOfGrammar** [comment]
How do you trigger a build manually?

**Comment by krame505** [comment]
I don't have access at the moment, but if you go to the Jenkins console at
http://coldpress.cs.umn.edu:8080/, you should be able to navigate melt-umn
-> silver -> feature/when-clauses where there should be an option to start
a build.  You will need to be logged in to Jenkins for that option to show
up (did we ever set up an account for you?)
Lucas Kramer

**Comment by RandomActsOfGrammar** [comment]
No, I don't have a Jenkins account that I know of.

**Comment by tedinski** [comment]
I might come in today, to take a look.

How’d you decide on the ‘when’ keyword?

Ted

**Comment by RandomActsOfGrammar** [comment]
OCaml, F#, and C# all use `when` for conditions on patterns.

**Comment by krame505** [comment]
The only language I am aware of that differs is Haskell, which uses `|` - but that would probably be more confusing for us as we already use it as our pattern separator.

**Pull request merged**
