### PR TITLE
Added propagate for functor attributes, try 2

### PR DESCRIPTION
**Pull request by krame505**
Previous pull request had something weird happen.  

I have added a production statement of the form
propagate functor foo, bar;
which generates synthesized equations for foo and bar to copy the tree using the same attributes. For children on which they do not occur, the child itself is used in the new tree.

### CODE REVIEW

**Comment by tedinski** [comment]
lgtm, as a first step.

**Comment by ericvanwyk** [comment]
Ted - what does "Igtm" mean in your comment?

Do you want to pull this in or not?

**Comment by tedinski** [comment]
Sorry, "looks good to me."

**Comment by ericvanwyk** [comment]
Ok, I'm merging.

**Pull request merged**
