### PR TITLE
Re-merge changes to terminals, monto, eclipse

### PR DESCRIPTION
**Pull request by tedinski**
With these additions, this branch shouldn't break eclipse (or any tests) anymore, once merged.

I'm going to triple-check that claim before I click commit, but @remexre were there any further concerns about this branch other than it broke eclipse? Good to merge?

### CODE REVIEW

**Comment by remexre** [comment]
I don't think there were any; should be fine.

**Comment by ericvanwyk** [comment]
So, is everything working now?

All the chatter has died down - hopefully you're all out enjoying the nice
weather now...

I spent my morning and early afternoon at the March for Science - very
cool.  Lots of people and clever signs.   "Grab 'em by the data" was one of
my favorites.

**Comment by tedinski** [comment]
I've managed to find another problem related to a totally separate change that sometimes breaks eclipse.

But that problem exists in `develop`, so I'm in favor of merging this. I'll make a fix and post that as a separate pull request.

re: day. I've been sick since monday. It's rough. Got a window open and a nice breeze though.

**Comment by ericvanwyk** [comment]
Sounds good.

Spring sickness is no fun.  Hope you're feeling better soon.

**Comment by tedinski** [comment]
Oh, nevermind, that problem doesn't exist in develop. I'm going to add a couple more commits here.

**Comment by tedinski** [comment]
Okay, can I bother you @remexre to just glance at those two new patches and see if you notice any issues? The second one is directly related to code you wrote. (As arguments to functions, Silver can take values or thunks that return values.)

**Comment by remexre** [comment]
lgtm

**Comment by tedinski** [comment]
Cool. deleting the branch or not is up to you.

**Comment by remexre** [comment]
I'll delete it, mine already has commits past it.

**Comment by tedinski** [comment]
Oh, I should do a publish-jars, shouldn't I?

Getting on that...

**Comment by ericvanwyk** [comment]
publish jars?  Is it not safe to just delete all the old ones.... :)

**Pull request merged**
