### PR TITLE
dc no longer passes a terminal to the intLiteral abstract production.

### PR DESCRIPTION
**Pull request by remexre**
Also, should I change the left-hand-sides of all the productions to `top`, to fit with what we do in other grammars?

### CODE REVIEW

**Comment by ericvanwyk** [comment]
<rant>No, do not change all lhs to 'top'.  This is not an established
convention and is, frankly, something that I do not like very much.  If
they all have the same name, then why bother giving the lhs a name...</rant>

**Comment by remexre** [comment]
I mean, I'd be fine making `top` a keyword (or keyword-by-convention) like `this` or `self` in most languages... Other than that, does this look good?

**Comment by ericvanwyk** [comment]
I'd say no to 'top' being a keyword.  Besides we have more important things
to worry about.

Otherwise this look good to me - go ahead and merge.

BTW, does this get tested in Jenkins?  Do any of the tutorials?

**Comment by tedinski** [comment]
I should probably write a FAQ entry about `top` someday.

But the short version is that it's exactly like `self` in Python. You can actually name it anything, but writing code without a "we always use a consistent name for this everywhere" rule is _awful_. The choice of `top` is unfortunate, but hey, I get to blame previous students for that! :D 

Eric has (what I think are) good reasons to not use `this`. I actually don't know that we've ever bothered to consider `self` because... you know... not important. Lots of better things to do.

> BTW, does this get tested in Jenkins? Do any of the tutorials?

They should all be, yes, but I haven't double checked that recently.

**Comment by krame505** [comment]
Agreed. It seems ugly, but makes copy/pasting and generally writing code
much simpler.

On May 24, 2017 10:18 AM, "Ted Kaminski" <notifications@github.com> wrote:

I should probably write a FAQ entry about top someday.

But the short version is that it's exactly like self in Python. You can
actually name it anything, but writing code without a "we always use a
consistent name for this everywhere" rule is *awful*. The choice of top is
unfortunate, but hey, I get to blame previous students for that! :D

Eric has (what I think are) good reasons to not use this. I actually don't
know that we've ever bothered to consider self because... you know... not
important. Lots of better things to do.

BTW, does this get tested in Jenkins? Do any of the tutorials?

They should all be, yes, but I haven't double checked that recently.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/melt-umn/silver/pull/170#issuecomment-303757176>, or mute
the thread

**Pull request merged**
