### PR TITLE
Change Default Associativity Behavior

### LINKED ISSUE #718: Support association = none
We currently support `association = left` and `association = right` for resolving shift/reduce conflicts between operators of the same precedence.  I thought we supported `association = none` for when we want to ban both the shift and reduce (i.e. make `x + y + z` a syntax error if `'+'` has `association = none`), but it seems we don't have syntax for this in Silver.  Copper does support this already.  

This could easily be fixed at the same time as #716.

### PR DESCRIPTION
**Pull request by keltono**
# Changes
* Adds `none` option for associativity
* Changes default behavior to not set associativity if not specified 
# Documentation
* No new documentation required, mostly just a modification of existing code

closes #718 and #716 .

### CODE REVIEW

**Comment by krame505** [comment]
> No new documentation required, mostly just a modification of existing code

https://melt.cs.umn.edu/silver/ref/decl/terminals/#terminal-association should probably be updated.

**Comment by krame505** [comment]
Also, looks like the tests are now failing

**Comment by keltono** [comment]
> Also, looks like the tests are now failing

Yeah I noticed this. I was going to ask about it in our meeting in a few minutes, since it's working on my machine :tm:..

**Review by krame505 — APPROVED** [review]
I _think_ the only blocker on this is that some of the downstream projects are failing?  That should be easy to fix.

**Pull request merged**
