### PR TITLE
Adds toString() for Booleans

### PR DESCRIPTION
**Pull request by remexre**
It does what it sounds like.

```
toString(true) == "true"
toString(false) == "false"
```

### CODE REVIEW

**Comment by tedinski** [comment]
This pull request seems to also have some vim stuff in it. Possibly branched from the wrong base branch?

My only immediate objection: I'd like to see the test cases added to the test suite. Should just be the two lines.

**Comment by remexre** [comment]
Oh, whoops. Yeah, I'll remove those and add the test cases.

**Comment by remexre** [comment]
Okay, I also added tests for the rest of the `toString()`-able types as well.

**Comment by tedinski** [comment]
Hah. I didn't know the float would output as 0.0.

Okay, looks good then.

**Comment by ericvanwyk** [comment]
Looks good - thanks Nathan.

**Pull request merged**
