### PR TITLE
Fix completeness checking for all whens

### LINKED ISSUE #546: Case completeness not checked when all clauses have whens
If every clause has a `when` condition, case completeness does not appear to trigger.  It should give a warning.

For example, this code
```
case 2 of                
| x when x == 3 -> true
end
```
should give a warning that the pattern matching is incomplete, but is accepted instead.

### PR DESCRIPTION
**Pull request by RandomActsOfGrammar**
# Changes
Fixes #546.  This checks if there are no patterns without `when` clauses but there are some match rules with `when` clauses. 
 In that case, it generates a warning for incomplete patterns.

# Documentation
I added a comment explaining the reason for the additional error check.  I also added a comment with the test to explain what it is checking.  This only affects the local code, so it doesn't need any further documentation elsewhere.  Its only effect visible to the user is in checking incomplete matching.

### CODE REVIEW

**Review by krame505 — COMMENTED** [review]
The comment on `checkCompleteness` should probably be updated - this function also returns `nothing()` if there are no (conditionless) patterns at all.

**Comment by RandomActsOfGrammar** [comment]
I don't see anything to update for the `checkCompleteness` comment.  This new check is separate from that one.  When we have no conditionless rules, `checkCompleteness` returns `nothing()`, which corresponds to no error.  Do you have a specific suggestion of what should be added there?

**Comment by krame505** [comment]
The comment says that `We return nothing() if the patterns are complete` - if there are no patterns, then they are clearly not complete.

**Comment by RandomActsOfGrammar** [comment]
One could also argue that it is complete if there are no identifiable missing patterns, but I see your point and added the comment in the interest of clarity.

**Comment by krame505** [comment]
I'm not sure how having no patterns whatsoever means that there are no identifiable missing patterns, since in that case any pattern would be a counterexample that isn't matched (unless the nonterminal being matched has no productions.)  So it still seems strange to me that `checkCompleteness` would return `nothing()` in that case, rather than choosing an arbitrary production as a counterexample.  

But it's probably fine as-is, I just found it slightly non-intuitive to handle the no-patterns case in this way.

**Review by krame505 — APPROVED** [review]

**Comment by RandomActsOfGrammar** [comment]
What is the purpose of the `complete` argument to the `caseExpr` production?  Is it to prevent checking for completeness in certain cases, like the `strategyattr` extension?

**Comment by krame505** [comment]
Yes, because rules in strategies are (almost always) incomplete matches, the translation inserts a default case that causes the strategy to fail.  We decorate a `caseExpr`  in order to perform normal error checking, and we still want to check for overlapping patterns, etc. however we don't want to error on incomplete matches.

**Pull request merged**
