### PR TITLE
More work on functor attributes

### PR DESCRIPTION
**Pull request by krame505**
Misc updates / fixes:
* Changed syntax as discussed
* Including the extension in the IDE spec
* Annotations are now copied from the current tree - before they were just missing
* Decorated nonterminals on the production RHS are now used directly, instead of copying by attribute.

### CODE REVIEW

**Comment by krame505** [comment]
1. That doesn't appear to be the case!  Without stripping the full name, I get errors "full:path:anno is not appropriate for <whatever>" and "missing annotation anno for <whatever>

**Comment by krame505** [comment]
2. I will fix that.

**Comment by krame505** [comment]
*3. That appears to be the case, I can change it.

**Comment by tedinski** [comment]
Re: 1. Huh. I'm thinking that's a bug then, though it's possible I'm forgetting something. I'll open an issue.

**Comment by tedinski** [comment]
Oh, and looks good, feel free to merge.

**Pull request merged**
